# Generated by Django 4.2.10 on 2024-03-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_vendors_alter_customers_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_work', models.TextField()),
                ('enquiry_date', models.DateField()),
                ('status', models.CharField(default='enquiry', max_length=20)),
                ('job_category', models.CharField(default='sales', max_length=20)),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('contact_person', models.CharField(max_length=50, null=True, unique=True)),
                ('sales_person', models.CharField(max_length=50, null=True, unique=True)),
                ('sales_team', models.CharField(max_length=20)),
                ('freight_type', models.CharField(choices=[('air freight', 'air freight'), ('sea freight', 'sea freight')], max_length=20)),
                ('type', models.CharField(default='export', max_length=20)),
                ('enquiry_details', models.TextField()),
                ('priority_tags', models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high')], default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_num', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update_Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
