# Generated by Django 4.2.10 on 2024-03-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_invoices_tracking_data_quotations_orders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approved_quotations',
            old_name='dimentions',
            new_name='dimensions',
        ),
    ]
