# Generated by Django 4.2.10 on 2024-03-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_enquiries_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='priority_tags',
            field=models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high')], max_length=20),
        ),
    ]
