# Generated by Django 4.2.10 on 2024-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_enquiries_priority_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='priority_tags',
            field=models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='status',
            field=models.CharField(default='Enquiry', max_length=20),
        ),
    ]
