# Generated by Django 4.2.10 on 2024-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_enquiries_email_alter_enquiries_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight_type', models.CharField(max_length=50)),
            ],
        ),
    ]
