# Generated by Django 4.2.10 on 2024-03-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_jobcategory_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotations',
            old_name='enquiry_date',
            new_name='quotation_date',
        ),
    ]
