# Generated by Django 4.2.10 on 2024-03-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_rename_enquiry_date_quotations_quotation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='terms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
