# Generated by Django 4.2.10 on 2024-03-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_quotations_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotations',
            old_name='dimensions',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='quotations',
            old_name='units',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='phone',
            field=models.CharField(default='1212121212', max_length=20),
        ),
    ]
