# Generated by Django 4.2.10 on 2024-03-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_rename_dimensions_quotations_dimension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotations',
            name='price',
        ),
    ]
