# Generated by Django 4.2.10 on 2024-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_remove_quotations_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
    ]
