# Generated by Django 4.2.10 on 2024-03-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_alter_quotations_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_quotations',
            name='sales_person',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='sales_person',
            field=models.CharField(default='', max_length=50),
        ),
    ]
