# Generated by Django 4.2.10 on 2024-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_alter_quotations_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shipping_agent_code',
        ),
        migrations.AddField(
            model_name='orders',
            name='flight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='notify_add',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='notify_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
