# Generated by Django 4.2.10 on 2024-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_remove_orders_date_remove_orders_shipping_agent_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='notify_acc',
            field=models.IntegerField(default=0),
        ),
    ]
