# Generated by Django 4.2.10 on 2024-03-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0024_remove_orders_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='consignee_address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='flight_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipper_acc_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipper_address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_agent_acc_num',
            field=models.IntegerField(),
        ),
    ]
