# Generated by Django 4.2.10 on 2024-03-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_alter_orders_consignee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='consignee_acc_num',
            field=models.IntegerField(),
        ),
    ]
