# Generated by Django 4.2.10 on 2024-03-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0027_login_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
