# Generated by Django 4.2.10 on 2024-03-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0028_delete_login_delete_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Enquiries',
            new_name='Enquirie',
        ),
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Quotations',
            new_name='Quotation',
        ),
        migrations.RenameModel(
            old_name='Shipping_Agents',
            new_name='Shipping_Agent',
        ),
        migrations.DeleteModel(
            name='Approved_Quotations',
        ),
    ]
