# Generated by Django 4.2.10 on 2024-04-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0029_rename_customers_customer_rename_enquiries_enquirie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirie',
            name='freight_type',
            field=models.CharField(choices=[('air freight', 'air freight'), ('sea freight', 'sea freight')], max_length=30),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='job_category',
            field=models.CharField(default='sales', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='phone',
            field=models.CharField(default='1212121212', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='priority_tags',
            field=models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high')], default='normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='sales_team',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='status',
            field=models.CharField(default='Enquiry', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquirie',
            name='type',
            field=models.CharField(default='export', max_length=30),
        ),
    ]
