# Generated by Django 4.2.10 on 2024-04-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0034_remove_order_enquiry_order_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirie',
            name='priority_tags',
        ),
    ]
