# Generated by Django 4.2.10 on 2024-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0041_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PREPARING', 'preparing'), ('CONFIRMED', 'confirmed'), ('PICKED UP', 'picked up'), ('IN WAREHOUSE', 'in warehouse'), ('IN TRANSIT', 'in transit'), ('DELIVERED', 'delivered')], default='preparing', max_length=25, null=True),
        ),
    ]
