# Generated by Django 4.2.10 on 2024-04-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(),
        ),
    ]
