# Generated by Django 4.2.10 on 2024-04-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0045_alter_quotation_quotation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('CONFIRMED', 'confirmed'), ('PICKED UP', 'picked up'), ('IN WAREHOUSE', 'in warehouse'), ('IN TRANSIT', 'in transit'), ('DELIVERED', 'delivered')], default='CONFIRMED', max_length=25, null=True),
        ),
    ]
