# Generated by Django 4.2.10 on 2024-04-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0046_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
