# Generated by Django 4.2.10 on 2024-04-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0047_quotation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipper_address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
