# Generated by Django 4.2.10 on 2024-04-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0048_remove_order_shipper_address_order_shipper_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flight_number',
            field=models.CharField(),
        ),
    ]
