# Generated by Django 4.2.10 on 2024-05-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0049_alter_order_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='consignee_address',
        ),
    ]
